name: Docker Scout

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  TAG: "my/app:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.5.0
      - uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          tags: ${{ env.TAG }}

      # --------------
      # Docker Scout
      # --------------

      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/scout-action@v1.0.9
        with:
          command: cves
          image: ${{ env.TAG }}
