name: Docker Scout

on:
  push:
  workflow_dispatch:

jobs:
  scout:
    uses: ./.github/workflows/scout.yml
    secrets:
      DOCKER_USER: "${{ secrets.DOCKER_USER }}"
      DOCKER_PAT: "${{ secrets.DOCKER_PAT }}"
    with:
      CONTEXT: "."
      TAG: "my/app:latest"
      REGISTRY: "docker.io"
